version: '3.8'

services:
  netmaker-server:
    image: gravitl/netmaker:latest
    container_name: netmaker-server
    volumes:
      - netmaker-data:/root/data
      - netmaker-certs:/etc/netmaker
    environment:
      - SERVER_NAME=broker.example.com
      - SERVER_API_CONN_STRING=api.example.com:8081
      - MASTER_KEY=TODO_REPLACE_MASTER_KEY
      - DATABASE=sqlite
      - NODE_ID=netmaker-server
      - MQ_HOST=netmaker-mq
      - MQ_PORT=1883
      - TELEMETRY=off
      - VERBOSITY=3
    cap_add:
      - NET_ADMIN
      - NET_RAW
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv6.conf.all.disable_ipv6=0
      - net.ipv6.conf.all.forwarding=1
    restart: unless-stopped
    pod: netmaker

  netmaker-mq:
    image: emqx/emqx:latest
    container_name: netmaker-mq
    volumes:
      - /home/jeremy/nm-setup-podman/config/emqx.conf:/opt/emqx/etc/emqx.conf:ro
      - netmaker-mq-data:/opt/emqx/data
      - netmaker-mq-logs:/opt/emqx/log
      - /home/jeremy/nm-setup-podman/config/emqx-certs:/etc/emqx/certs:ro
    environment:
      - EMQX_NODE__NAME=emqx@netmaker-mq
      - EMQX_NODE__COOKIE=f8ab55b3be9805e70c729fd62ea8fdfe
      - EMQX_NODE__DATA_DIR=/opt/emqx/data
      - EMQX_NODE__DB_BACKEND=mnesia
      - EMQX_CLUSTER__PROTO_DIST=inet_tcp
      - EMQX_NODE__DIST_NET_TICKTIME=120
    restart: unless-stopped
    pod: netmaker

  netmaker-ui:
    image: gravitl/netmaker-ui:latest
    container_name: netmaker-ui
    environment:
      - BACKEND_URL=https://api.example.com:8081
    restart: unless-stopped
    pod: netmaker

  netmaker-proxy:
    image: nginx
    container_name: netmaker-proxy
    volumes:
      - /home/jeremy/nm-setup-podman/config/nginx.conf:/etc/nginx/nginx.conf:ro
      - /home/jeremy/nm-setup-podman/config/selfsigned.key:/etc/nginx/ssl/selfsigned.key
      - /home/jeremy/nm-setup-podman/config/selfsigned.crt:/etc/nginx/ssl/selfsigned.crt
    restart: unless-stopped
    pod: netmaker

volumes:
  netmaker-data:
  netmaker-mq-data:
  netmaker-mq-logs:
  netmaker-certs:
